-- Active: 1788267993342@@127.0.0.1@3306@smartcoffee_dml_manu
-- REVISÃO DE DML - AULA 8

-- REVISÃO INSERT

INSERT INTO CLIENTE (NOME, EMAIL, TELEFONE, CIDADE, ATIVO) VALUES
('KAUAN M ', 'KAUANM@EMAIL.COM', '1999999900', 'LIMEIRA', FALSE),
('LAURA C', 'LAURAC@EMAIL.COM', '1999999901', 'LIMEIRA', TRUE),
('LAURA N', 'LAURAN@EMAIL.COM', '1999999902', 'LIMEIRA', TRUE),
('LAURA R', 'LAURAR@EMAIL.COM', '1999999903', 'LIMEIRA', TRUE),
('LEONARDO B', 'LEONARDOB@EMAIL.COM', '1999999904', 'LIMEIRA', TRUE),
('LEONARDO BT', 'LEONARDOBT@EMAIL.COM', '1999999905', 'AMERICAN', TRUE),
('LIDIA M', 'LIDIAM@EMAIL.COM', '1999999906', 'BELEM', TRUE),
('LIVIA', 'LIVIA@EMAIL.COM', '1999999998', 'LIMEIRA', TRUE),
('MARCOS V', 'MACOSV@EMAIL.COM', '1999999907', 'LIMEIRA', TRUE),
('NICOLAS N', 'CHINAN@EMAIL.COM', '1999999908', 'LIMEIRA', FALSE),
('NICOLAS F', 'LOMBAS@EMAIL.COM', '1999999909', 'CAMPINAS', TRUE),
('PABLO H', 'MICROONDAS@EMAIL.COM', '1999999910', 'LIMEIRA', TRUE),
('SOPHIE A', 'SOPEHH@EMAIL.COM', '1999999922', 'INDAIATUDA', TRUE),
('VINICIOS H', 'VINECEOSSS@EMAIL.COM', NULL, 'LIMEIRA', TRUE),
('VITORIA S', 'VIVIBORA@EMAIL.COM', '1999999921', 'LIMEIRA', FALSE),
('VIRGINIA S', 'VIRGINIA@EMAIL.COM', '1999999934', 'BOSTON', TRUE);
 SELECT * FROM CLIENTE;

INSERT INTO CATEGORIA (NOME_CATEGORIA)VALUES
('COMBOS ESPECIAIS'), ('NUTELLA');

INSERT INTO PEDIDO ( DATA_PEDIDO, STATUS_PEDIDO, VALOR_TOTAL, ID_CLIENTE)VALUES
(NOW(), 'PENDENTE',0.00,20);

SET @PEDIDO = LAST_INSERT_ID();
SELECT @PEDIDO;

INSERT INTO ITEM_PEDIDO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE, PRECO_UNITARIO, OBSERVACAO) VALUES
(@PEDIDO, 25, 2, 13.00, 'NUTELLA');

-- ATUALIZANDO DADOS NO BD
UPDATE CLIENTE
SET TELEFONE = '19981215360',
    CIDADE = 'SANTA CATARINA',
    ATIVO = FALSE
WHERE ID_CLIENTE = 11;
-- TOMAR MUITO CUIDADO-------- NAO ESQUECER :(
UPDATE CLIENTE
SET ATIVO = FALSE;

UPDATE PEDIDO 
SET VALOR_TOTAL = 1.00;
----------------------------------------------------------
-- DICAS DE OURO
-- EXECUTAR O SELECT SEMPRE ANTES DE ATUALIZAR
-- SELECT * FROMM TEBELA_QUE_DESEJO
----------------------------------------------------------
-- CONDICIONAIS
UPDATE PRODUTO
SET PRECO =
CASE 
    WHEN PRECO < 30 THEN  PRECO * 1.50  
    ELSE  PRECO * 1.25
END
WHERE ATIVO = TRUE;

UPDATE CLIENTE
SET TELEFONE = NULL
WHERE ID_CLIENTE = 14;
-- APAGANDO DADOS DO BD
DELETE FROM CLIENTE
WHERE ID_CLIENTE = 18;

TRUNCATE TABLE CLIENTE;

-- EXCLUINDO DADOS DE FORMA LOGICA
UPDATE CLIENTE
SET ATIVO = FALSE 
WHERE ID_CLIENTE = 20;
-- ---------------------------------------------------------
-- CADASTRANDO UM PROCEDIMENTO DE COMPRA
INSERT INTO CLIENTE (NOME, EMAIL, TELEFONE, CIDADE, ATIVO) VALUES
('BRUNO', 'BRUNINHO@EMAIL','12345678909', 'PIRACICABA', TRUE);
SET @CLIENTE = LAST_INSERT_ID();
-- PASSO 2: ADICIONANDO UM NOVO PEDIDO
INSERT INTO PEDIDO (DATA_PEDIDO, STATUS_PEDIDO, VALOR_TOTAL, ID_CLIENTE) VALUES
(NOW(),'PENDENTE', 0.00,@CLIENTE);

SET @PEDIDO = LAST_INSERT_ID();
-- PASSO 3: ADICIONANDO ITENS AO PEDIDO
INSERT INTO ITEM_PEDIDO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE, PRECO_UNITARIO, OBSERVACAO) VALUES
(@PEDIDO, 24, 2, 13.00,'MEL'),
(@PEDIDO, 25, 1, 15.00, '');

-- PASSO 4: ATUALIZANOD O VALOR TOTAL NDO PEDIDO
UPDATE PEDIDO
SET VALOR_TOTAL = 22.00,
    STATUS_PEDIDO = 'PROCESSANDO'
WHERE ID_PEDIDO = @PEDIDO;

-- PASSO 5: REGISTRANDO PAGAMNTO
INSERT INTO PAGAMENTO (ID_PEDIDO, ID_FORMA_PAGAMENTO, VALOR, DATA_PAGAMENTO) VALUES
(@PEDIDO, 2, 22.00, NOW());

-- CONSULTA DE FORMA COMPLETA
SELECT P.ID_PEDIDO,
     C.NOME AS CLIENTE,
     P.STATUS_PEDIDO,
     P.VALOR_TOTAL
FROM PEDIDO P
JOIN CLIENTE C ON C.ID_CLIENTE = P.ID_CLIENTE
WHERE P.ID_PEDIDO  = @PEDIDO;

-- CONSULTA PARA OS DADOS NO BCD 
SELECT * FROM PRODUTO;
SELECT * FROM CLIENTE;
WHERE ID_CLIENTE = 20;