-- Active: 1788267993342@@127.0.0.1@3306@smartcoffee_dml_manu
--- SMARTCOFFEE BASE DE DADOS - DML 
--- EXECUTE SEMPRE QUE QUISER RESTAURAR A AULA.

DROP DATABASE IF EXISTS SMARTCOFFEE_DML_manu;
CREATE DATABASE SMARTCOFFEE_DML_manu;
USE SMARTCOFFEE_DML_manu;

-- TABELAS
CREATE TABLE CLIENTE (
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(120) NOT NULL UNIQUE,
    TELEFONE VARCHAR(15),
   CIDADE VARCHAR(50) NOT NULL,
   ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
   DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CATEGORIA (
    ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    NOME_CATEGORIA VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE PRODUTO (
    ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PRODUTO VARCHAR(100) NOT NULL,
    PRECO DECIMAL(10, 2) NOT NULL,
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    ID_CATEGORIA INT NOT NULL,
    -- REFERENCIA DE NOMENCLATURA DE FOREIGN KEY, SEMPRE ACRESENTAR ESS TIPO DE DADO
    CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);

CREATE TABLE PEDIDO (
    ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    DATA_PEDIDO DATETIME NOT NULL,
    STATUS_PEDIDO ENUM('PENDENTE', 'PROCESSANDO', 'ENVIADO', 'ENTREGUE', 'CANCELADO') NOT NULL,
    VALOR_TOTAL DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    ID_CLIENTE INT NOT NULL,
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE ITEM_PEDIDO (
    ID_ITEM_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    PRECO_UNITARIO DECIMAL(10, 2) NOT NULL,
    OBSERVACAO VARCHAR(150),
    CONSTRAINT FK_ITEM_PEDIDO_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
    CONSTRAINT FK_ITEM_PEDIDO_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);

CREATE TABLE FORMA_PAGAMENTO (
    ID_FORMA_PAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE PAGAMENTO (
    ID_PAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT NOT NULL,
    ID_FORMA_PAGAMENTO INT NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL,
    DATA_PAGAMENTO DATETIME,
    CONSTRAINT FK_PAGAMENTO_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
    CONSTRAINT FK_PAGAMENTO_FORMA_PAGAMENTO FOREIGN KEY (ID_FORMA_PAGAMENTO) REFERENCES FORMA_PAGAMENTO(ID_FORMA_PAGAMENTO)
);

-- INSERCAO DE DADOS
INSERT INTO CLIENTE (NOME, EMAIL, TELEFONE, CIDADE, ATIVO, DATA_CADASTRO) VALUES
('ANA SILVA', 'ANA@EMAIL.COM', '19999990001', 'LIMEIRA', TRUE, NULL),
('BRUNO SOUZA', 'BRUONO@EMAIL.COM', '19999990002', 'RIO CLARO', TRUE, NULL),
('CARLOS PEREIRA', 'CARLOS@EMAIL.COM', '19999990003', 'ARRARAS', TRUE, NULL),
('DANIELA COSTA', 'DANIELA@EMAIL.COM', '19999990004', 'LIMEIRA', TRUE, NULL),
('LIVIA SANTANA', 'LILIHBOA@EMAIL.COM', '19999990005', 'CAMPIBAS', TRUE, NULL),
('LIDIA ELIANA', 'LILIHMA@EMAIL.COM', '19999990006', 'LIMEIRA', TRUE, NULL),
('LEONARDO', 'TETECO@EMAIL.COM', '19999990007', 'LIMEIRA', TRUE, NULL),
('CAHULIN', 'CHAULINDOPENEL@EMAIL.COM', '19999990008', 'AMERICANA', TRUE, NULL);
SELECT * FROM CLIENTE 

INSERT INTO CATEGORIA (NOME_CATEGORIA) VALUES
('CAFÉ'),
('BEBIDAS QUNTES'),
('BEBIDAS GELADAS'),
('SOBREMESAS'),
('LANCHES'),
('DOCES'),
('SANDUÍCHES'),
('SALGADOS');
SELECT * FROM CATEGORIA

INSERT INTO PRODUTO (NOME_PRODUTO, PRECO, ATIVO, ID_CATEGORIA) VALUES
('EXPRESSO', 5.00, TRUE, 1),
('AGUA', 2.50, TRUE, 3),
('CAPUCCINO', 7.50, TRUE, 1),
('LATTE', 6.50, TRUE, 1),
('MOCHA', 8.00, TRUE, 1),
('NUTELLA LATTE', 9.00, TRUE, 1),
('CHOCOLATE QUENTE', 4.50, TRUE, 2),
('CHÁ VERDE', 3.00, TRUE, 2),
('CHÁ PRETO', 3.00, TRUE, 2),
('REFRIGERANTE LATA', 4.00, TRUE, 3),
('SUCO NATURAL', 5.00, TRUE, 3),
('ÁGUA MINERAL', 2.50, TRUE, 3),
('BOLO DE CHOCOLATE', 6.00, TRUE, 4),
('TORTA DE LIMÃO', 7.00, TRUE, 4),
('SORVETE DE BAUNILHA', 5.50, TRUE, 4),
('SANDUÍCHE NATURAL', 8.00, TRUE, 5),
('SANDUÍCHE DE FRANGO', 9.00, TRUE, 5),
('PASTEL DE CARNE', 4.50, TRUE, 6),
('PASTEL DE QUEIJO', 4.50, TRUE, 6),
('CROISSANT', 5.00, TRUE, 7),
('BAURU', 7.50, TRUE, 7),
('PÃO DE QUEIJO', 3.50, TRUE, 7),
('EMPADA DE FRANGO', 4.00, TRUE, 8);
SELECT * FROM PRODUTO

INSERT INTO PEDIDO (DATA_PEDIDO, STATUS_PEDIDO, VALOR_TOTAL, ID_CLIENTE) VALUES
('2024-06-01 10:00:00', 'PENDENTE', 15.00, 1),
('2024-06-02 11:30:00', 'PROCESSANDO', 20.50, 2),
('2024-06-03 14:15:00', 'ENVIADO', 12.75, 3),
('2024-06-04 09:45:00', 'ENTREGUE', 18.00, 4),
('2024-06-04 15:30:00', 'ENTREGUE', 22.00, 4),
('2024-06-05 12:00:00', 'CANCELADO', 10.00, 5),
('2024-06-05 13:15:00', 'PENDENTE', 30.00, 6),
('2024-06-05 16:20:00', 'CANCELADO', 25.00, 5),
(now(), 'aberto', 0.00, 8);

set @PEDIDO = LAST_INSERT_ID();
SELECT @PEDIDO;
SELECT * FROM PEDIDO

INSERT INTO ITEM_PEDIDO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE, PRECO_UNITARIO, OBSERVACAO) VALUES
(1, 1, 2, 5.00, 'Sem açúcar'),
(1, 6, 1, 4.50, NULL),
(2, 2, 1, 7.50, 'Com chantilly'),
(2, 9, 2, 4.00, NULL),
(3, 3, 1, 6.50, NULL),
(3, 12, 1, 6.00, 'Sem cobertura'),
(4, 4, 2, 8.00, NULL),
(4, 15, 1, 8.00, 'Sem maionese'),
(5, 5, 1, 9.00, NULL),
(5, 10, 2, 5.00, 'Sem gelo'),
(6, 7, 1, 3.00, NULL),
(6, 18, 2, 4.50, 'Com catupiry'),
(7, 11, 3, 2.50, NULL),
(7, 20, 1, 7.50, 'Sem tomate'),
(8, 13, 1, 7.00, NULL),
(8 ,19 ,2 ,5.00 ,NULL);
SELECT * FROM ITEM_PEDIDO

INSERT INTO FORMA_PAGAMENTO (DESCRICAO) VALUES
('DINHEIRO'),
('CARTÃO DE CRÉDITO'),
('CARTÃO DE DÉBITO'),
('PIX'),
('VALE REFEIÇÃO');
SELECT * FROM FORMA_PAGAMENTO;

INSERT INTO PAGAMENTO (ID_PEDIDO, ID_FORMA_PAGAMENTO, VALOR, DATA_PAGAMENTO) VALUES
(1, 1, 15.00, '2024-06-01 10:30:00'),
(6, 1, 10.00, '2024-06-05 12:30:00'),
(7, 2, 30.00, '2024-06-05 13:45:00'),
(5, 4, 22.00, NOW()),
(8, 3, 25.00, '2024-06-05 16:50:00');
SELECT * FROM PAGAMENTO;

-- UPDATE OU ATUALIZAÇÃO DE DADOS 
UPDATE CLIENTE 
SET TELEFONE = '19999990210'
WHERE ID_CLIENTE = 3;
SELECT * FROM CLIENTE;

SELECT * FROM CLIENTE
WHERE ID_CLIENTE= 3;

UPDATE CLIENTE
SET TELEFONE = '19981215360',
    CIDADE = 'RIO CLARO'
WHERE ID_CLIENTE = 5;
SELECT * FROM CLIENTE
WHERE ID_CLIENTE= 5;

-- UPDATE PRODUTO 
UPDATE PRODUTO
SET PRECO = PRECO * 1.05
WHERE ID_PRODUTO = 1;
SELECT *FROM PRODUTO
WHERE ID_PRODUTO = 1;

-- EX 5
UPDATE PRODUTO
SET PRECO = CASE 
    WHEN PRECO < 10 THEN PRECO * 1.10  
    ELSE  PRECO *1.05
END
WHERE ATIVO = TRUE;
SELECT * FROM PRODUTO;

-- EX 6
UPDATE CLIENTE
SET TELEFONE = NULL
WHERE ID_CLIENTE = 5;
SELECT * FROM CLIENTE;

-- EXCLUIR REGISTROS 
DELETE FROM CLIENTE
WHERE ID_CLIENTE = 8;
SELECT * FROM CLIENTE;

-- EX 
TRUNCATE TABLE CLIENTE;

-- ex 7 
UPDATE PRODUTO 
SET ATIVO = FALSE
WHERE ID_PRODUTO = 17;

UPDATE cliente
SET ATIVO = FALSE
WHERE ID_CLIENTE = 8;




SELECT 'BANCO DE DADOS SMARTCOFFEE_DML_NAZARETH CRIADO COM SUCESSO!' AS mensagem;